/*
 * Copyright (c) 2012-present Snowplow Analytics Ltd.
 * All rights reserved.
 *
 * This software is made available by Snowplow Analytics, Ltd.,
 * under the terms of the Snowplow Limited Use License Agreement, Version 1.1
 * located at https://docs.snowplow.io/limited-use-license-1.1
 * BY INSTALLING, DOWNLOADING, ACCESSING, USING OR DISTRIBUTING ANY PORTION
 * OF THE SOFTWARE, YOU AGREE TO THE TERMS OF SUCH LICENSE AGREEMENT.
 */

package com.snowplowanalytics.snowplow.databricks

import cats.Id
import cats.effect.testing.specs2.CatsEffect
import cats.effect.IO
import org.http4s.implicits._
import com.comcast.ip4s.Port
import org.apache.parquet.hadoop.metadata.CompressionCodecName
import org.specs2.Specification

import java.nio.file.Paths
import scala.concurrent.duration.DurationInt

import com.snowplowanalytics.snowplow.runtime.{AcceptedLicense, ConfigParser, HttpClient, Retrying, Telemetry, Webhook}
import com.snowplowanalytics.snowplow.streams.kinesis.{BackoffPolicy, KinesisSinkConfig, KinesisSinkConfigM, KinesisSourceConfig}

class KinesisConfigSpec extends Specification with CatsEffect {
  import KinesisConfigSpec._

  def is = s2"""
   Config parse should be able to parse
    minimal kinesis config $minimal
  """

  private def minimal = {
    val path = Paths.get(getClass.getResource("/config.kinesis.minimal.hocon").toURI)
    ConfigParser.configFromFile[IO, Config[Unit, KinesisSourceConfig, KinesisSinkConfig]](path).value.map { result =>
      result must beRight(expectedMinimalConfig)
    }
  }
}

object KinesisConfigSpec {
  private val expectedMinimalConfig = Config[Unit, KinesisSourceConfig, KinesisSinkConfig](
    input = KinesisSourceConfig(
      appName                          = "snowplow-databricks-loader",
      streamName                       = "snowplow-enriched-events",
      workerIdentifier                 = "test-hostname",
      initialPosition                  = KinesisSourceConfig.InitialPosition.Latest,
      retrievalMode                    = KinesisSourceConfig.Retrieval.Polling(1000),
      customEndpoint                   = None,
      dynamodbCustomEndpoint           = None,
      cloudwatchCustomEndpoint         = None,
      leaseDuration                    = 10.seconds,
      maxLeasesToStealAtOneTimeFactor  = BigDecimal("2.0"),
      checkpointThrottledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
      debounceCheckpoints              = 10.seconds
    ),
    output = Config.Output(
      good = Config.Databricks(
        host        = "https://<identifier>.cloud.databricks.com",
        token       = None,
        oauth       = Some(Config.DatabricksOAuth(clientId = "test-client-id", clientSecret = "test-secret")),
        catalog     = "snowplow",
        schema      = "atomic",
        volume      = "snowplow",
        compression = CompressionCodecName.SNAPPY
      ),
      bad = Config.SinkWithMaxSize(
        sink = KinesisSinkConfigM[Id](
          streamName             = "bad",
          throttledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
          recordLimit            = 500,
          byteLimit              = 5242880,
          customEndpoint         = None
        ),
        maxRecordSize = 1000000
      )
    ),
    streams = (),
    batching = Config.Batching(
      maxBytes          = 16000000,
      maxDelay          = 1.second,
      uploadConcurrency = 3
    ),
    retries = Config.Retries(
      setupErrors     = Retrying.Config.ForSetup(delay = 30.seconds),
      transientErrors = Retrying.Config.ForTransient(delay = 1.second, attempts = 5)
    ),
    telemetry = Telemetry.Config(
      disable         = false,
      interval        = 15.minutes,
      collectorUri    = uri"https://collector-g.snowplowanalytics.com",
      userProvidedId  = None,
      autoGeneratedId = None,
      instanceId      = None,
      moduleName      = None,
      moduleVersion   = None
    ),
    monitoring = Config.Monitoring(
      metrics     = Config.Metrics(None),
      sentry      = None,
      healthProbe = Config.HealthProbe(port = Port.fromInt(8000).get, unhealthyLatency = 5.minutes),
      webhook     = Webhook.Config(endpoint = None, tags = Map.empty, heartbeat = 5.minutes)
    ),
    license                 = AcceptedLicense(),
    skipSchemas             = List.empty,
    exitOnMissingIgluSchema = true,
    http                    = Config.Http(HttpClient.Config(4)),
    dev                     = Config.DevFeatures(setEtlTstamp = false)
  )
}
